### ISSUE TITLE
Non time-gated events

### ISSUE THREAD

**Issue by jorgenbuilder** [sagacards/bazaar#57]
I want to transition Legends NFTs away from time gated hype events (read: bear market.) So, events should be either supply based or just unlimited.

**Comment by di-wu** [comment]
https://github.com/sagacards/bazaar/blob/78cad1f9b78480b72c8f61323223a387ef6e56ec/src/Events/lib.mo#L254-L257

Since `Time.Time` is an `Int`, we can just set it to `-1` to set it to 'unlimited'.
You would just need to update the following:
https://github.com/sagacards/bazaar/blob/78cad1f9b78480b72c8f61323223a387ef6e56ec/src/Events/lib.mo#L264-L268
